from datetime import datetime

sets = {
	'lea': { 'code' : 'LEA', 'date' : '1993-08', 'name' : 'Alpha (Limited Edition)', 'description' : '(1E) - Core set - Core set #1 (1st printing); Cards do not show the expansion symbol.' },
	'leb': { 'code' : 'LEB', 'date' : '1993-10', 'name' : 'Beta (Limited Edition)', 'description' : '(2E) - Core set - Core set #1 (2nd printing); Cards do not show the expansion symbol.' },
	'2ed': { 'code' : '2ED', 'date' : '1993-12', 'name' : 'Unlimited Edition', 'description' : '(2U) - Core set - Core set #2; Cards do not show the expansion symbol.' },
	'arn': { 'code' : 'ARN', 'date' : '1993-12', 'name' : 'Arabian Nights', 'description' : '(AN) - Expansion set - 1st (non-block) expansion' },
	'atq': { 'code' : 'ATQ', 'date' : '1994-03', 'name' : 'Antiquities', 'description' : '(AQ) - Expansion set - 2nd (non-block) expansion' },
	'3ed': { 'code' : '3ED', 'date' : '1994-04', 'name' : 'Revised Edition', 'description' : '(3E) - Core set - Core set #3; Cards do not show the expansion symbol.' },
	'leg': { 'code' : 'LEG', 'date' : '1994-06', 'name' : 'Legends', 'description' : '(LE) - Expansion set - 3rd (non-block) expansion' },
	'drk': { 'code' : 'DRK', 'date' : '1994-08', 'name' : 'The Dark', 'description' : '(DK) - Expansion set - 4th (non-block) expansion' },
	'fem': { 'code' : 'FEM', 'date' : '1994-11', 'name' : 'Fallen Empires', 'description' : '(FE) - Expansion set - 5th (non-block) expansion' },
	'4ed': { 'code' : '4ED', 'date' : '1995-05', 'name' : 'Fourth Edition', 'description' : '(4E) - Core set - Core set #4; Cards do not show the expansion symbol.' },
	'ice': { 'code' : 'ICE', 'date' : '1995-06', 'name' : 'Ice Age', 'description' : '(IA) - Expansion set - 6th expansion' },
	'chr': { 'code' : 'CHR', 'date' : '1995-07', 'name' : 'Chronicles', 'description' : '(CH) - Compilation set' },
	'hml': { 'code' : 'HML', 'date' : '1995-10', 'name' : 'Homelands', 'description' : '(HM) - Expansion set - 7th (non-block) expansion' },
	'all': { 'code' : 'ALL', 'date' : '1996-06', 'name' : 'Alliances', 'description' : '(AL) - Expansion set - 8th expansion' },
	'mir': { 'code' : 'MIR', 'date' : '1996-10', 'name' : 'Mirage', 'description' : '(MI) - Expansion set - 9th expansion' },
	'vis': { 'code' : 'VIS', 'date' : '1997-02', 'name' : 'Visions', 'description' : '(VI) - Expansion set - 10th expansion' },
	'5ed': { 'code' : '5ED', 'date' : '1997-03', 'name' : 'Fifth Edition', 'description' : '(5E) - Core set - Core set #5; Cards do not show the expansion symbol.' },
	'por': { 'code' : 'POR', 'date' : '1997-05', 'name' : 'Portal', 'description' : '(PO) - Starter set - Starter set #1' },
	'wth': { 'code' : 'WTH', 'date' : '1997-06', 'name' : 'Weatherlight', 'description' : '(WL) - Expansion set - 11th expansion' },
	'tmp': { 'code' : 'TMP', 'date' : '1997-10', 'name' : 'Tempest', 'description' : '(TE) - Expansion set - 12th expansion' },
	'sth': { 'code' : 'STH', 'date' : '1998-02', 'name' : 'Stronghold', 'description' : '(ST) - Expansion set - 13th expansion' },
	'exo': { 'code' : 'EXO', 'date' : '1998-06', 'name' : 'Exodus', 'description' : '(EX) - Expansion set - 14th expansion' },
	'p02': { 'code' : 'P02', 'date' : '1998-06', 'name' : 'Portal Second Age', 'description' : '(P2) - Starter set - Starter set #2' },
	'ugl': { 'code' : 'UGL', 'date' : '1998-08', 'name' : 'Unglued', 'description' : '(UG) - Un-set - Un-set #1' },
	'usg': { 'code' : 'USG', 'date' : '1998-10', 'name' : 'Urza\'s Saga', 'description' : '(UZ) - Expansion set - 15th expansion' },
	'ath': { 'code' : 'ATH', 'date' : '1998-11', 'name' : 'Anthologies', 'description' : 'Box set - First box set' },
	'ulg': { 'code' : 'ULG', 'date' : '1999-02', 'name' : 'Urza\'s Legacy', 'description' : '(GU) - Expansion set - 16th expansion' },
	'6ed': { 'code' : '6ED', 'date' : '1999-04', 'name' : 'Sixth Edition', 'description' : '(6E) - Core set - Core set #6' },
	'uds': { 'code' : 'UDS', 'date' : '1999-06', 'name' : 'Urza\'s Destiny', 'description' : '(CG) - Expansion set - 17th expansion' },
	'ptk': { 'code' : 'PTK', 'date' : '1999-07', 'name' : 'Portal Three Kingdoms', 'description' : '(PK) - Starter set - Starter set #3' },
	's99': { 'code' : 'S99', 'date' : '1999-08', 'name' : 'Starter 1999', 'description' : '(P3) - Starter set - Starter set #4' },
	'mmq': { 'code' : 'MMQ', 'date' : '1999-09', 'name' : 'Mercadian Masques', 'description' : '(MM) - Expansion set - 18th expansion' },
	'brb': { 'code' : 'BRB', 'date' : '1999-11', 'name' : 'Battle Royale', 'description' : 'Box set' },
	'nem': { 'code' : 'NEM', 'date' : '2000-02', 'name' : 'Nemesis', 'description' : '(NE) - Expansion set - 19th expansion' },
	's00': { 'code' : 'S00', 'date' : '2000-04', 'name' : 'Starter 2000', 'description' : 'Starter set - Starter set #5' },
	'pcy': { 'code' : 'PCY', 'date' : '2000-06', 'name' : 'Prophecy', 'description' : '(PR) - Expansion set - 20th expansion' },
	'inv': { 'code' : 'INV', 'date' : '2000-09', 'name' : 'Invasion', 'description' : '(IN) - Expansion set - 21st expansion' },
	'btd': { 'code' : 'BTD', 'date' : '2000-10', 'name' : 'Beatdown', 'description' : 'Box set' },
	'pls': { 'code' : 'PLS', 'date' : '2001-01', 'name' : 'Planeshift', 'description' : '(PS) - Expansion set - 22nd expansion' },
	'7ed': { 'code' : '7ED', 'date' : '2001-04', 'name' : 'Seventh Edition', 'description' : '(7E) - Core set - Core set #7' },
	'apc': { 'code' : 'APC', 'date' : '2001-05', 'name' : 'Apocalypse', 'description' : '(AP) - Expansion set - 23rd expansion' },
	'ody': { 'code' : 'ODY', 'date' : '2001-10', 'name' : 'Odyssey', 'description' : '(OD) - Expansion set - 24th expansion' },
	'dkm': { 'code' : 'DKM', 'date' : '2001-12', 'name' : 'Deckmasters 2001', 'description' : 'Box set' },
	'tor': { 'code' : 'TOR', 'date' : '2002-02', 'name' : 'Torment', 'description' : '(TO) - Expansion set - 25th expansion' },
	'jud': { 'code' : 'JUD', 'date' : '2002-05', 'name' : 'Judgment', 'description' : '(JU) - Expansion set - 26th expansion' },
	'ons': { 'code' : 'ONS', 'date' : '2002-10', 'name' : 'Onslaught', 'description' : '(ON) - Expansion set - 27th expansion' },
	'lgn': { 'code' : 'LGN', 'date' : '2003-01', 'name' : 'Legions', 'description' : '(LE) - Expansion set - 28th expansion' },
	'scg': { 'code' : 'SCG', 'date' : '2003-05', 'name' : 'Scourge', 'description' : '(SC) - Expansion set - 29th expansion' },
	'8ed': { 'code' : '8ED', 'date' : '2003-07', 'name' : 'Eighth Edition', 'description' : '(8E) - Core set - Core set #8' },
	'mrd': { 'code' : 'MRD', 'date' : '2003-10', 'name' : 'Mirrodin', 'description' : 'Expansion set - 30th expansion' },
	'dst': { 'code' : 'DST', 'date' : '2004-02', 'name' : 'Darksteel', 'description' : 'Expansion set - 31st expansion' },
	'5dn': { 'code' : '5DN', 'date' : '2004-06', 'name' : 'Fifth Dawn', 'description' : 'Expansion set - 32nd expansion' },
	'chk': { 'code' : 'CHK', 'date' : '2004-10', 'name' : 'Champions of Kamigawa', 'description' : 'Expansion set - 33rd expansion' },
	'unh': { 'code' : 'UNH', 'date' : '2004-11', 'name' : 'Unhinged', 'description' : 'Un-set - Un-set #2' },
	'bok': { 'code' : 'BOK', 'date' : '2005-02', 'name' : 'Betrayers of Kamigawa', 'description' : 'Expansion set - 34th expansion' },
	'sok': { 'code' : 'SOK', 'date' : '2005-06', 'name' : 'Saviors of Kamigawa', 'description' : 'Expansion set - 35th expansion' },
	'9ed': { 'code' : '9ED', 'date' : '2005-07', 'name' : 'Ninth Edition', 'description' : 'Core set - Core set #9' },
	'rav': { 'code' : 'RAV', 'date' : '2005-10', 'name' : 'Ravnica: City of Guilds', 'description' : 'Expansion set - 36th expansion' },
	'gpt': { 'code' : 'GPT', 'date' : '2006-02', 'name' : 'Guildpact', 'description' : 'Expansion set - 37th expansion' },
	'dis': { 'code' : 'DIS', 'date' : '2006-05', 'name' : 'Dissension', 'description' : 'Expansion set - 38th expansion' },
	'csp': { 'code' : 'CSP', 'date' : '2006-07', 'name' : 'Coldsnap', 'description' : 'Expansion set - 39th expansion' },
	'tsp': { 'code' : 'TSP', 'date' : '2006-10', 'name' : 'Time Spiral', 'description' : 'Expansion set - 40th expansion' },
	'plc': { 'code' : 'PLC', 'date' : '2007-02', 'name' : 'Planar Chaos', 'description' : 'Expansion set - 41st expansion' },
	'fut': { 'code' : 'FUT', 'date' : '2007-05', 'name' : 'Future Sight', 'description' : 'Expansion set - 42nd expansion' },
	'10e': { 'code' : '10E', 'date' : '2007-07', 'name' : 'Tenth Edition', 'description' : 'Core set - Core set #10' },
	'me1': { 'code' : 'MED', 'date' : '2007-09', 'name' : 'Masters Edition', 'description' : 'Compilation set - Magic Online Masters set #1' },
	'lrw': { 'code' : 'LRW', 'date' : '2007-10', 'name' : 'Lorwyn', 'description' : 'Expansion set - 43rd expansion' },
	'evg': { 'code' : 'EVG', 'date' : '2007-11', 'name' : 'Duel Decks: Elves vs. Goblins', 'description' : 'Box set - Duel Decks set #1' },
	'mor': { 'code' : 'MOR', 'date' : '2008-02', 'name' : 'Morningtide', 'description' : 'Expansion set - 44th expansion' },
	'shm': { 'code' : 'SHM', 'date' : '2008-05', 'name' : 'Shadowmoor', 'description' : 'Expansion set - 45th expansion' },
	'eve': { 'code' : 'EVE', 'date' : '2008-06', 'name' : 'Eventide', 'description' : 'Expansion set - 46th expansion' },
	'drb': { 'code' : 'DRB', 'date' : '2008-08', 'name' : 'From the Vault: Dragons', 'description' : 'Box set - From the Vault set #1' },
	'me2': { 'code' : 'ME2', 'date' : '2008-09', 'name' : 'Masters Edition II', 'description' : 'Compilation set - Magic Online Masters set #2' },
	'ala': { 'code' : 'ALA', 'date' : '2008-09', 'name' : 'Shards of Alara', 'description' : 'Expansion set - 47th expansion' },
	'jvc': { 'code' : 'DD2', 'date' : '2008-11', 'name' : 'Duel Decks: Jace vs. Chandra', 'description' : 'Box set - Duel Decks set #2' },
	'con': { 'code' : 'CON', 'date' : '2009-02', 'name' : 'Conflux', 'description' : 'Expansion set - 48th expansion' },
	'dvd': { 'code' : 'DVD', 'date' : '2009-04', 'name' : 'Duel Decks: Divine vs. Demonic', 'description' : 'Box set - Duel Decks set #3' },
	'arb': { 'code' : 'ARB', 'date' : '2009-04', 'name' : 'Alara Reborn', 'description' : 'Expansion set - 49th expansion' },
	'm10': { 'code' : 'M10', 'date' : '2009-07', 'name' : 'Magic 2010', 'description' : 'Core set - Core set #11' },
	'td0': { 'code' : 'TD0', 'date' : '2009-08', 'name' : 'Commander Theme Decks', 'description' : 'Box set - Magic Online only' },
	'v09': { 'code' : 'V09', 'date' : '2009-08', 'name' : 'From the Vault: Exiled', 'description' : 'Box set - From the Vault set #2' },
	'hop': { 'code' : 'HOP', 'date' : '2009-09', 'name' : 'Planechase', 'description' : 'Supplemental set - Planechase set #1' },
	'me3': { 'code' : 'ME3', 'date' : '2009-09', 'name' : 'Masters Edition III', 'description' : 'Compilation set - Magic Online Masters set #3' },
	'zen': { 'code' : 'ZEN', 'date' : '2009-10', 'name' : 'Zendikar', 'description' : 'Expansion set - 50th expansion' },
	'gvl': { 'code' : 'DDD', 'date' : '2009-10', 'name' : 'Duel Decks: Garruk vs. Liliana', 'description' : 'Box set - Duel Decks set #4' },
	'h09': { 'code' : 'H09', 'date' : '2009-11', 'name' : 'Premium Deck Series: Slivers', 'description' : 'Box set - Premium Deck Series set #1' },
	'wwk': { 'code' : 'WWK', 'date' : '2010-02', 'name' : 'Worldwake', 'description' : 'Expansion set - 51st expansion' },
	'dde': { 'code' : 'DDE', 'date' : '2010-03', 'name' : 'Duel Decks: Phyrexia vs. The Coalition', 'description' : 'Box set - Duel Decks set #5' },
	'roe': { 'code' : 'ROE', 'date' : '2010-04', 'name' : 'Rise of the Eldrazi', 'description' : 'Expansion set - 52nd expansion' },
	'dpa': { 'code' : 'DPA', 'date' : '2010-06', 'name' : 'Duels of the Planeswalkers', 'description' : 'Box set - Inspired by the digital game' },
	'arc': { 'code' : 'ARC', 'date' : '2010-06', 'name' : 'Archenemy', 'description' : 'Supplemental set - Archenemy set #1' },
	'm11': { 'code' : 'M11', 'date' : '2010-07', 'name' : 'Magic 2011', 'description' : 'Core set - Core set #12' },
	'v10': { 'code' : 'V10', 'date' : '2010-08', 'name' : 'From the Vault: Relics', 'description' : 'Box set - From the Vault set #3' },
	'ddf': { 'code' : 'DDF', 'date' : '2010-09', 'name' : 'Duel Decks: Elspeth vs. Tezzeret', 'description' : 'Box set - Duel Decks set #6' },
	'som': { 'code' : 'SOM', 'date' : '2010-10', 'name' : 'Scars of Mirrodin', 'description' : 'Expansion set - 53rd expansion' },
	'td0': { 'code' : 'TD0', 'date' : '2010-11', 'name' : 'Magic Online Deck Series', 'description' : 'Box set - Magic Online only; Same set code and symbol as the Commander Theme Decks' },
	'pd2': { 'code' : 'PD2', 'date' : '2010-11', 'name' : 'Premium Deck Series: Fire & Lightning', 'description' : 'Box set - Premium Deck Series set #2' },
	'me4': { 'code' : 'ME4', 'date' : '2011-01', 'name' : 'Masters Edition IV', 'description' : 'Compilation set - Magic Online Masters set #4' },
	'mbs': { 'code' : 'MBS', 'date' : '2011-02', 'name' : 'Mirrodin Besieged', 'description' : 'Expansion set - 54th expansion' },
	'ddg': { 'code' : 'DDG', 'date' : '2011-04', 'name' : 'Duel Decks: Knights vs. Dragons', 'description' : 'Box set - Duel Decks set #7' },
	'nph': { 'code' : 'NPH', 'date' : '2011-05', 'name' : 'New Phyrexia', 'description' : 'Expansion set - 55th expansion' },
	'cmd': { 'code' : 'CMD', 'date' : '2011-06', 'name' : 'Commander', 'description' : 'Box set - Commander set #1' },
	'm12': { 'code' : 'M12', 'date' : '2011-07', 'name' : 'Magic 2012', 'description' : 'Core set - Core set #13' },
	'v11': { 'code' : 'V11', 'date' : '2011-08', 'name' : 'From the Vault: Legends', 'description' : 'Box set - From the Vault set #4' },
	'ddh': { 'code' : 'DDH', 'date' : '2011-09', 'name' : 'Duel Decks: Ajani vs. Nicol Bolas', 'description' : 'Box set - Duel Decks set #8' },
	'isd': { 'code' : 'ISD', 'date' : '2011-09', 'name' : 'Innistrad', 'description' : 'Expansion set - 56th expansion' },
	'pd3': { 'code' : 'PD3', 'date' : '2011-11', 'name' : 'Premium Deck Series: Graveborn', 'description' : 'Box set - Premium Deck Series set #3' },
	'dka': { 'code' : 'DKA', 'date' : '2012-02', 'name' : 'Dark Ascension', 'description' : 'Expansion set - 57th expansion' },
	'ddi': { 'code' : 'DDI', 'date' : '2012-03', 'name' : 'Duel Decks: Venser vs. Koth', 'description' : 'Box set - Duel Decks set #9' },
	'avr': { 'code' : 'AVR', 'date' : '2012-05', 'name' : 'Avacyn Restored', 'description' : 'Expansion set - 58th expansion' },
	'pc2': { 'code' : 'PC2', 'date' : '2012-05', 'name' : 'Planechase 2012', 'description' : 'Supplemental set - Planechase set #2' },
	'm13': { 'code' : 'M13', 'date' : '2012-07', 'name' : 'Magic 2013', 'description' : 'Core set - Core set #14' },
	'v12': { 'code' : 'V12', 'date' : '2012-08', 'name' : 'From the Vault: Realms', 'description' : 'Box set - From the Vault set #5' },
	'ddj': { 'code' : 'DDJ', 'date' : '2012-09', 'name' : 'Duel Decks: Izzet vs. Golgari', 'description' : 'Box set - Duel Decks set #10' },
	'rtr': { 'code' : 'RTR', 'date' : '2012-10', 'name' : 'Return to Ravnica', 'description' : 'Expansion set - 59th expansion' },
	'cm1': { 'code' : 'CM1', 'date' : '2012-11', 'name' : 'Commander\'s Arsenal', 'description' : 'Box set - Commander set #2' },
	'td2': { 'code' : 'TD2', 'date' : '2013-01', 'name' : 'Duel Decks: Mirrodin Pure vs. New Phyrexia', 'description' : 'Box set - Magic Online Duel Deck' },
	'gtc': { 'code' : 'GTC', 'date' : '2013-02', 'name' : 'Gatecrash', 'description' : 'Expansion set - 60th expansion' },
	'ddk': { 'code' : 'DDK', 'date' : '2013-03', 'name' : 'Duel Decks: Sorin vs. Tibalt', 'description' : 'Box set - Duel Decks set #11' },
	'dgm': { 'code' : 'DGM', 'date' : '2013-05', 'name' : 'Dragon\'s Maze', 'description' : 'Expansion set - 61st expansion' },
	'mma': { 'code' : 'MMA', 'date' : '2013-06', 'name' : 'Modern Masters', 'description' : 'Compilation set - Masters set #1' },
	'm14': { 'code' : 'M14', 'date' : '2013-07', 'name' : 'Magic 2014', 'description' : 'Core set - Core set #15' },
	'v13': { 'code' : 'V13', 'date' : '2013-08', 'name' : 'From the Vault: Twenty', 'description' : 'Box set - From the Vault set #6' },
	'ddl': { 'code' : 'DDL', 'date' : '2013-09', 'name' : 'Duel Decks: Heroes vs. Monsters', 'description' : 'Box set - Duel Decks set #12' },
	'ths': { 'code' : 'THS', 'date' : '2013-09', 'name' : 'Theros', 'description' : 'Expansion set - 62nd expansion' },
	'c13': { 'code' : 'C13', 'date' : '2013-11', 'name' : 'Commander 2013', 'description' : 'Box set - Commander set #3' },
	'bng': { 'code' : 'BNG', 'date' : '2014-02', 'name' : 'Born of the Gods', 'description' : 'Expansion set - 63rd expansion' },
	'ddm': { 'code' : 'DDM', 'date' : '2014-03', 'name' : 'Duel Decks: Jace vs. Vraska', 'description' : 'Box set - Duel Decks set #13' },
	'jou': { 'code' : 'JOU', 'date' : '2014-05', 'name' : 'Journey into Nyx', 'description' : 'Expansion set - 64th expansion' },
	'md1': { 'code' : 'MD1', 'date' : '2014-05', 'name' : 'Modern Event Deck', 'description' : 'Box set' },
	'cns': { 'code' : 'CNS', 'date' : '2014-06', 'name' : 'Conspiracy', 'description' : 'Supplemental set - Conspiracy set #1' },
	'vma': { 'code' : 'VMA', 'date' : '2014-06', 'name' : 'Vintage Masters', 'description' : 'Compilation set - Magic Online Masters set #5' },
	'm15': { 'code' : 'M15', 'date' : '2014-07', 'name' : 'Magic 2015', 'description' : 'Core set - Core set #16' },
	'v14': { 'code' : 'V14', 'date' : '2014-08', 'name' : 'From the Vault: Annihilation', 'description' : 'Box set - From the Vault set #7' },
	'ddn': { 'code' : 'DDN', 'date' : '2014-10', 'name' : 'Duel Decks: Speed vs. Cunning', 'description' : 'Box set - Duel Decks set #14' },
	'ktk': { 'code' : 'KTK', 'date' : '2014-10', 'name' : 'Khans of Tarkir', 'description' : 'Expansion set - 65th expansion' },
	'c14': { 'code' : 'C14', 'date' : '2014-11', 'name' : 'Commander 2014', 'description' : 'Box set - Commander set #4' },
	'dd3': { 'code' : 'DD3', 'date' : '2014-12', 'name' : 'Duel Decks Anthology', 'description' : 'Box set - Duel Decks reprint set' },
	'frf': { 'code' : 'FRF', 'date' : '2015-01', 'name' : 'Fate Reforged', 'description' : 'Expansion set - 66th expansion' },
	'ddo': { 'code' : 'DDO', 'date' : '2015-02', 'name' : 'Duel Decks: Elspeth vs. Kiora', 'description' : 'Box set - Duel Decks set #15' },
	'dtk': { 'code' : 'DTK', 'date' : '2015-03', 'name' : 'Dragons of Tarkir', 'description' : 'Expansion set - 67th expansion' },
	'tpr': { 'code' : 'TPR', 'date' : '2015-05', 'name' : 'Tempest Remastered', 'description' : 'Compilation set - Magic Online Masters set #6' },
	'mm2': { 'code' : 'MM2', 'date' : '2015-05', 'name' : 'Modern Masters 2015', 'description' : 'Compilation set - Masters set #2' },
	'ori': { 'code' : 'ORI', 'date' : '2015-07', 'name' : 'Magic Origins', 'description' : 'Core set - Core set #17' },
	'v15': { 'code' : 'V15', 'date' : '2015-08', 'name' : 'From the Vault: Angels', 'description' : 'Box set - From the Vault set #8' },
	'ddp': { 'code' : 'DDP', 'date' : '2015-08', 'name' : 'Duel Decks: Zendikar vs. Eldrazi', 'description' : 'Box set - Duel Decks set #16' },
	'bfz': { 'code' : 'BFZ', 'date' : '2015-10', 'name' : 'Battle for Zendikar', 'description' : 'Expansion set - 68th expansion' },
	'exp': { 'code' : 'EXP', 'date' : '2016-01', 'name' : 'Zendikar Expeditions', 'description' : 'Compilation set - Masterpiece Series set #1 (Battle for Zendikar block)' },
	'c15': { 'code' : 'C15', 'date' : '2015-11', 'name' : 'Commander 2015', 'description' : 'Box set - Commander set #5' },
	'pz1': { 'code' : 'PZ1', 'date' : '2015-11', 'name' : 'Legendary Cube', 'description' : 'Compilation set - Magic Online only' },
	'ogw': { 'code' : 'OGW', 'date' : '2016-01', 'name' : 'Oath of the Gatewatch', 'description' : 'Expansion set - 69th expansion' },
	'ddq': { 'code' : 'DDQ', 'date' : '2016-02', 'name' : 'Duel Decks: Blessed vs. Cursed', 'description' : 'Box set - Duel Decks set #17' },
	'w16': { 'code' : 'W16', 'date' : '2016-04', 'name' : 'Welcome Deck 2016', 'description' : 'Compilation set - Welcome Deck set #1' },
	'soi': { 'code' : 'SOI', 'date' : '2016-04', 'name' : 'Shadows over Innistrad', 'description' : 'Expansion set - 70th expansion' },
	'ema': { 'code' : 'EMA', 'date' : '2016-06', 'name' : 'Eternal Masters', 'description' : 'Compilation set - Masters set #3' },
	'emn': { 'code' : 'EMN', 'date' : '2016-07', 'name' : 'Eldritch Moon', 'description' : 'Expansion set - 71st expansion' },
	'v16': { 'code' : 'V16', 'date' : '2016-08', 'name' : 'From the Vault: Lore', 'description' : 'Box set - From the Vault set #9' },
	'cn2': { 'code' : 'CN2', 'date' : '2016-08', 'name' : 'Conspiracy: Take the Crown', 'description' : 'Supplemental set - Conspiracy set #2' },
	'ddr': { 'code' : 'DDR', 'date' : '2016-09', 'name' : 'Duel Decks: Nissa vs. Ob Nixilis', 'description' : 'Box set - Duel Decks set #18' },
	'kld': { 'code' : 'KLD', 'date' : '2016-09', 'name' : 'Kaladesh', 'description' : 'Expansion set - 72nd expansion' },
	'mps': { 'code' : 'MPS', 'date' : '2017-01', 'name' : 'Kaladesh Inventions', 'description' : 'Compilation set - Masterpiece Series set #2 (Kaladesh block)' },
	'pz2': { 'code' : 'PZ2', 'date' : '2016-10', 'name' : 'Treasure Chests', 'description' : 'Compilation set - Magic Online only' },
	'c16': { 'code' : 'C16', 'date' : '2016-11', 'name' : 'Commander 2016', 'description' : 'Box set - Commander set #6' },
	'pca': { 'code' : 'PCA', 'date' : '2016-11', 'name' : 'Planechase Anthology', 'description' : 'Box set - Planechase set #3' },
	'aer': { 'code' : 'AER', 'date' : '2017-01', 'name' : 'Aether Revolt', 'description' : 'Expansion set - 73rd expansion' },
	'mm3': { 'code' : 'MM3', 'date' : '2017-03', 'name' : 'Modern Masters 2017', 'description' : 'Compilation set - Masters set #4' },
	'dds': { 'code' : 'DDS', 'date' : '2017-03', 'name' : 'Duel Decks: Mind vs. Might', 'description' : 'Box set - Duel Decks set #19' },
	'w17': { 'code' : 'W17', 'date' : '2017-04', 'name' : 'Welcome Deck 2017', 'description' : 'Compilation set - Welcome Deck set #2' },
	'akh': { 'code' : 'AKH', 'date' : '2017-04', 'name' : 'Amonkhet', 'description' : 'Expansion set - 74th expansion' },
	'mps': { 'code' : 'MPS', 'date' : '2017-07', 'name' : 'Amonkhet Invocations', 'description' : 'Compilation set - Masterpiece Series set #3 (Amonkhet block)' },
	'cma': { 'code' : 'CMA', 'date' : '2017-06', 'name' : 'Commander Anthology', 'description' : 'Box set - Commander set #7' },
	'e01': { 'code' : 'E01', 'date' : '2017-06', 'name' : 'Archenemy: Nicol Bolas', 'description' : 'Supplemental set - Archenemy set #2, Annex set #1' },
	'hou': { 'code' : 'HOU', 'date' : '2017-07', 'name' : 'Hour of Devastation', 'description' : 'Expansion set - 75th expansion' },
	'c17': { 'code' : 'C17', 'date' : '2017-08', 'name' : 'Commander 2017', 'description' : 'Box set - Commander set #8' },
	'xln': { 'code' : 'XLN', 'date' : '2017-09', 'name' : 'Ixalan', 'description' : 'Expansion set - 76th expansion' },
	'ddt': { 'code' : 'DDT', 'date' : '2017-11', 'name' : 'Duel Decks: Merfolk vs. Goblins', 'description' : 'Box set - Duel Decks set #20' },
	'ima': { 'code' : 'IMA', 'date' : '2017-11', 'name' : 'Iconic Masters', 'description' : 'Compilation set - Masters set #5' },
	'e02': { 'code' : 'E02', 'date' : '2017-11', 'name' : 'Explorers of Ixalan', 'description' : 'Supplemental set - Annex set #2' },
	'v17': { 'code' : 'V17', 'date' : '2017-11', 'name' : 'From the Vault: Transform', 'description' : 'Box set - From the Vault set #10' },
	'ust': { 'code' : 'UST', 'date' : '2017-12', 'name' : 'Unstable', 'description' : 'Un-set - Un-set #3' },
	'rix': { 'code' : 'RIX', 'date' : '2018-01', 'name' : 'Rivals of Ixalan', 'description' : 'Expansion set - 77th expansion' },
	'a25': { 'code' : 'A25', 'date' : '2018-03', 'name' : 'Masters 25', 'description' : 'Compilation set - Masters set #6' },
	'ddu': { 'code' : 'DDU', 'date' : '2018-04', 'name' : 'Duel Decks: Elves vs. Inventors', 'description' : 'Box set - Duel Decks set #21' },
	'q01': { 'code' : 'Q01', 'date' : '2018-04', 'name' : 'Challenger Decks', 'description' : 'Box set - Challenger Decks set #1' },
	'dom': { 'code' : 'DOM', 'date' : '2018-04', 'name' : 'Dominaria', 'description' : 'Expansion set - 78th expansion' },
	'cm2': { 'code' : 'CM2', 'date' : '2018-06', 'name' : 'Commander Anthology Volume II', 'description' : 'Box set - Commander set #9' },
	'bbd': { 'code' : 'BBD', 'date' : '2018-06', 'name' : 'Battlebond', 'description' : 'Supplemental set' },
	'ss1': { 'code' : 'SS1', 'date' : '2018-06', 'name' : 'Signature Spellbook: Jace', 'description' : 'Box set - Signature Spellbook set #1' },
	'gs1': { 'code' : 'GS1', 'date' : '2018-06', 'name' : 'Global Series: Jiang Yanggu & Mu Yanling', 'description' : 'Box set - Global Series set #1' },
	'm19': { 'code' : 'M19', 'date' : '2018-07', 'name' : 'Core Set 2019', 'description' : 'Core set - Core set #18' },
	'c18': { 'code' : 'C18', 'date' : '2018-08', 'name' : 'Commander 2018', 'description' : 'Box set - Commander set #10' },
	'med': { 'code' : 'MED', 'date' : '2018-10', 'name' : 'Guilds of Ravnica Mythic Edition', 'description' : 'Special edition' },
	'grn': { 'code' : 'GRN', 'date' : '2018-10', 'name' : 'Guilds of Ravnica', 'description' : 'Expansion set - 79th expansion' },
	'sk1': { 'code' : 'SK1', 'date' : '2018-10', 'name' : 'Spellslinger Starter Kit', 'description' : 'Box set' },
	'gk1': { 'code' : 'GK1', 'date' : '2018-11', 'name' : 'Guilds of Ravnica Guild Kits', 'description' : 'Box set - Annex set #4, 1st set of Guild Kits' },
	'gnt': { 'code' : 'GNT', 'date' : '2018-11', 'name' : 'Game Night', 'description' : 'Box set' },
	'uma': { 'code' : 'UMA', 'date' : '2018-12', 'name' : 'Ultimate Masters', 'description' : 'Compilation set - Masters set #7' },
	'rna': { 'code' : 'RNA', 'date' : '2019-01', 'name' : 'Ravnica Allegiance', 'description' : 'Expansion set - 80th expansion' },
	'gk2': { 'code' : 'GK2', 'date' : '2019-02', 'name' : 'Ravnica Allegiance Guild Kits', 'description' : 'Box set - Annex set #5, 2nd set of Guild Kits' },
	'q02': { 'code' : 'Q02', 'date' : '2019-04', 'name' : 'Challenger Decks 2019', 'description': 'Box set - Challenger Decks set #2'},
	'med': { 'code' : 'MED', 'date' : '2019-05', 'name' : 'War of the Spark Mythic Edition', 'description': 'Special edition'},
	'war': { 'code' : 'WAR', 'date' : '2019-05', 'name' : 'War of the Spark', 'description': 'Expansion set - 81st expansion'},
	'mh1': { 'code' : 'MH1', 'date' : '2019-06', 'name' : 'Modern Horizons', 'description': 'Supplemental set'},
	'ss2': { 'code' : 'SS2', 'date' : '2019-06', 'name' : 'Signature Spellbook: Gideon', 'description': 'Box set - Signature Spellbook set #2'},
	'm20': { 'code' : 'M20', 'date' : '2019-07', 'name' : 'Core Set 2020', 'description': 'Core set - Core set #19'},
	'c19': { 'code' : 'C19', 'date' : '2019-08', 'name' : 'Commander 2019', 'description': 'Box set - Commander set #10'},
	'eld': { 'code' : 'ELD', 'date' : '2019-10', 'name' : 'Throne of Eldraine', 'description': 'Expansion set - 82nd expansion'},
	'gn2': { 'code' : 'GN2', 'date' : '2019-11', 'name' : 'Game Night 2019', 'description': 'Box set - Game Night set #2'},
	'sld': { 'code' : 'SLD', 'date' : '2019-12', 'name' : 'Secret Lair Drop Series', 'description': 'Box set - Secret Lair set #1'},
	'thb': { 'code' : 'THB', 'date' : '2020-01', 'name' : 'Theros Beyond Death', 'description': 'Expansion set - 83rd expansion'},
	'usd': { 'code' : 'USD', 'date' : '2020-02', 'name' : 'Unsanctioned', 'description': 'Box set - Un-set #4'},
	'iko' : { 'code' : 'IKO', 'date' : '2020-04', 'name' : 'Ikoria: Lair of Behemoths', 'description' : 'Expansion set - 84th expansion'},
	'c20' : { 'code' : 'C20', 'date' : '2020-04', 'name' : 'Commander 2020', 'description' : 'Box set - Commander set #11'},
	'sld' : { 'code' : 'SLD', 'date' : '2020-05', 'name' : 'Secret Lair Drop Series: The Godzilla Lands', 'description' : 'Box set - Secret Lair release #7'},
	'sld' : { 'code' : 'SLD', 'date' : '2020-06', 'name' : 'Secret Lair Drop Series: Summer Superdrop', 'description' : 'Box set - Secret Lair release #8'},
	'slu' : { 'code' : 'SLU', 'date' : '2020-06', 'name' : 'Secret Lair: Ultimate Edition', 'description' : 'Box set - Secret Lair release #9'},
	'ss3' : { 'code' : 'SS3', 'date' : '2020-06', 'name' : 'Signature Spellbook: Chandra', 'description' : 'Box set - Signature Spellbook set #3'},
	'm21' : { 'code' : 'M21', 'date' : '2020-07', 'name' : 'Core Set 2021', 'description' : 'Core set - Core set #20'},
	'jmp' : { 'code' : 'JMP', 'date' : '2020-07', 'name' : 'Jumpstart', 'description' : 'Supplemental set'},
	'2xm' : { 'code' : '2XM', 'date' : '2020-08', 'name' : 'Double Masters', 'description' : 'Compilation set - Masters set #8'},
	'akr' : { 'code' : 'AKR', 'date' : '2020-08', 'name' : 'Amonkhet Remastered', 'description' : 'Compilation set - MTG Arena set #1'},
	'sld' : { 'code' : 'SLD', 'date' : '2020-08', 'name' : 'Secret Lair Drop Series: Prime Slime', 'description' : 'Box set - Secret Lair release #10'},
	'sld' : { 'code' : 'SLD', 'date' : '2020-08', 'name' : 'Secret Lair Drop Series: Every Dog Has Its Day', 'description' : 'Box set - Secret Lair release #11'},
	'znr' : { 'code' : 'ZNR', 'date' : '2020-09', 'name' : 'Zendikar Rising', 'description' : 'Expansion set - 85th expansion'},
	'zne' : { 'code' : 'ZNE', 'date' : '2020-09', 'name' : 'Zendikar Rising Expeditions', 'description' : 'Compilation set - Masterpiece Series set #4'},
	'znc' : { 'code' : 'ZNC', 'date' : '2020-09', 'name' : 'Zendikar Rising Commander Decks', 'description' : 'Box set - Commander Decks set #1'},
	'cmr' : { 'code' : 'CMR', 'date' : '2020-11', 'name' : 'Commander Legends', 'description' : 'Supplemental set'},
	'cmc' : { 'code' : 'CMC', 'date' : '2020-11', 'name' : 'Commander Legends Commander Decks', 'description' : 'Box set - Commander Decks set #2'},
	'cc1' : { 'code' : 'CC1', 'date' : '2020-12', 'name' : 'Commander Collection: Green', 'description' : 'Box set - Commander Collection #1'},
	'sld' : { 'code' : 'SLD', 'date' : '2020-11', 'name' : "Secret Lair Drop Series: Extra Life 2020", 'description' : 'Box set - Secret Lair release #12' },
	'sld' : { 'code' : 'SLD', 'date' : '2020-11', 'name' : "Secret Lair Drop Series: Secretversary", 'description' : 'Box set - Secret Lair release #13' },
	'khm' : { 'code' : 'KHM', 'date' : '2021-02', 'name' : "Kaldheim", 'description' : 'Expansion set - 86th expansion' },
	'khc' : { 'code' : 'KHC', 'date' : '2021-02', 'name' : "Kaldheim Commander Decks", 'description' : 'Box set - Commander Decks set #3' },
	'sld' : { 'code' : 'SLD', 'date' : '2021-02', 'name' : "Secret Lair Drop Series: Smitten", 'description' : 'Box set - Secret Lair release #14' },
	'sld' : { 'code' : 'SLD', 'date' : '2021-02', 'name' : "Secret Lair Drop Series: Black is Magic", 'description' : 'Box set - Secret Lair release #15' },
	'tsr' : { 'code' : 'TSR', 'date' : '2021-03', 'name' : "Time Spiral Remastered", 'description' : 'Expansion set - Masters set #9' },
	'q04' : { 'code' : 'Q04', 'date' : '2021-03', 'name' : "Challenger Decks 2021", 'description' : 'Box set - Challenger Decks set #4' },
	'stx' : { 'code' : 'STX', 'date' : '2021-04', 'name' : "Strixhaven: School of Mages", 'description' : 'Expansion set - 87th expansion' },
	'sta' : { 'code' : 'STA', 'date' : '2021-04', 'name' : "Mystical Archive", 'description' : 'Compilation set' },
	'c21' : { 'code' : 'C21', 'date' : '2021-04', 'name' : "Commander 2021", 'description' : 'Expansion set - Commander set #12' },
	'slu' : { 'code' : 'SLU', 'date' : '2021-05', 'name' : "Secret Lair: Ultimate Edition 2", 'description' : 'Box set - Secret Lair release #15' },
	'mh2' : { 'code' : 'MH2', 'date' : '2021-06', 'name' : "Modern Horizons 2", 'description' : 'Supplemental set - Straight to Modern set #2' }

}

def getSetDate(set):
	if set in sets:
		return datetime.strptime(sets[set]["date"], "%Y-%m")
	else:
		return datetime.min

def getSetOrder(set):
	if set in sets:
		return sets[set]["date"] + sets[set]["name"]
	else:
		print ("unknown set '" + set + "'")
		return set

def getSetName(set):
	if set in sets:
		return sets[set]["name"]
	else:
		print ("unknown set '" + set + "'")
		return set